CREATE TABLE IF NOT EXISTS BorrowRequests (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  BorrowerID INT NOT NULL,
  ItemName VARCHAR(20) NOT NULL,
  Comments TEXT,
  CategoryID INT NOT NULL,
  StartTime DATETIME NOT NULL,
  EndTime DATETIME NOT NULL,
  Price INT
);
